language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "2.6"
  - "pypy"
services:
  - redis-server
install:
  - pip install -e .
  - pip install coveralls pytest-cov>=2.2.0

script: py.test --cov . --cov-config .coveragerc

after_success:
  coveralls
